name: Deploy to Production

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 888577024605.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY: rails-app
  RAILS_ENV: production
  EC2_HOST: 13.60.250.114

jobs:
  deploy:
    name: Deploy Latest Image to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          if [ -z "$SSH_KEY" ]; then
            echo "ERROR: EC2_SSH_KEY secret is not set!"
            exit 1
          fi
          printf '%s\n' "$SSH_KEY" > ~/.ssh/rails-demo.pem
          chmod 600 ~/.ssh/rails-demo.pem
          ssh-keyscan -H ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Deploy with Kamal (Latest Image)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: kamal deploy

      - name: Verify deployment
        run: |
          sleep 10
          curl -f http://${{ env.EC2_HOST }}/health || exit 1

      - name: Deployment successful
        run: echo "✅ Deployment to production completed successfully!"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Deployment failed! Check logs above."

